### ISSUE TITLE
システムコール

### ISSUE THREAD

**Issue by YuyaAizawa** [wadachi-ware/wadachi-os#1]
UARTへの出力をシステムコールとして実装する．

**Comment by YuyaAizawa** [comment]
x86_64 での実装例の資料
http://yuma.ohgami.jp/x86_64-Jisaku-OS-3.pdf

**Comment by Iwancof** [comment]
システムコールとして実装するなら当然特権周りから実装していく必要があるので、まずはそこからやらないと、という感じですね。
